name: test-suite

on:
  push:
    branches:
      - stable
      - 'pr/*'
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Deny warnings in CI
  # Disable debug info (see https://github.com/sigp/lighthouse/issues/4005)
  RUSTFLAGS: "-D warnings -C debuginfo=0"
  # Prevent Github API rate limiting.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Enable self-hosted runners for the Anchor repo only.
  SELF_HOSTED_RUNNERS: false # ${{ github.repository == 'sigp/anchor' }}
  # Self-hosted runners need to reference a different host for `./watch` tests.
  WATCH_HOST: ${{ github.repository == 'sigp/anchor' && 'host.docker.internal' || 'localhost' }}
  # Disable incremental compilation
  CARGO_INCREMENTAL: 0
  # Enable portable to prevent issues with caching `blst` for the wrong CPU type
  # TEST_FEATURES: portable
jobs:
  check-labels:
    runs-on: ubuntu-latest
    name: Check for 'skip-ci' label
    outputs:
      skip_ci: ${{ steps.set-output.outputs.SKIP_CI }}
    steps:
     - name: check for skip-ci label
       id: set-output
       env:
         LABELS: ${{ toJson(github.event.pull_request.labels) }}
       run: |
         SKIP_CI="false"
         if [ -z "${LABELS}" ]  || [ "${LABELS}" = "null" ]; then
           LABELS="none";
         else
           LABELS=$(echo ${LABELS} | jq -r '.[].name')
         fi
         for label in ${LABELS}; do
           if [ "$label" = "skip-ci" ]; then
             SKIP_CI="true"
             break
           fi
         done
         echo "skip_ci=$SKIP_CI" >> $GITHUB_OUTPUT

  target-branch-check:
    name: target-branch-check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    steps:
        - name: Check that the pull request is not targeting the stable branch
          run: |
            if [[ "${{ github.base_ref }}" == "stable" && "${{ github.head_ref }}" != "unstable" ]]; then
              echo "Pull requests to the stable branch can only come from the unstable branch."
              exit 1
            fi
  